### ISSUE TITLE
BUG: getCache(cache_...) is deprecated and trigger an error in typo3 10

### ISSUE THREAD

**Issue by RTPAst** [b13/menus#47]
Accessing a cache with the "cache_" prefix as in "cache_hash" and "cache_pages" is not necessary anymore, and should be called without the cache prefix. fix is needed in Classes/Hooks/DataHandlerHook.php

**Comment by RTPAst** [comment]
You can use TYPO3\CMS\Core\Information\Typo3Version for backward-compatibility

**Comment by lochmueller** [comment]
Hey everyone....
on the StaticFileCache slack we found out, that SFC is not deleted, because only two caches are deleted. Should we call a flush by tags on the manager, to support all configured caches?
https://api.typo3.org/master/class_t_y_p_o3_1_1_c_m_s_1_1_core_1_1_cache_1_1_cache_manager.html#ae8af86d7af4c26e4d6aae11ab07585fd
Regards,
Tim
